### ISSUE TITLE
GetLanguageServiceGuid NullReferenceException 

### ISSUE THREAD

**Issue by OzBob** [justcla/HotSettings#12]
VS2017 15.8.3
Hot Settings v 1.2.1

This NullReferenceException happened once, on start up of newly installed VSIX, for the first load of Visual Studio, while a large web solution was loading.

It has not been reported since.

Here is the Activity Log entry:

  <entry>
    <record>2877</record>
    <time>2018/09/10 03:41:08.489</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: 
	Object reference not set to an instance of an object.
	at HotSettings.HotSettingsCommandsTextViewCreationListener.GetLanguageServiceGuid(IWpfTextView textView) in C:\Projects\HotSettings\HotSettings\HotSettingsCommandsTextViewCreationListener.cs:line 49
	at HotSettings.HotSettingsCommandsTextViewCreationListener.VsTextViewCreated(IVsTextView textViewAdapter) in C:\Projects\HotSettings\HotSettings\HotSettingsCommandsTextViewCreationListener.cs:line 36
	at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.<>c__DisplayClass423_0.<SendVsTextViewCreated>b__0()
	at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
	--- End of stack trace from previous location where exception was thrown ---
	at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>

**Comment by justcla** [comment]
Hey OzBob. Thanks for raising the issue. I'm aware of it. When opening the Diff Viewer, it doesn't detect a language type and nulls get past through everywhere.
I haven't had the time to fix it. But if you can have a crack at it, that would be great. I don't think I'll get to fix it for a while. (And it bugs me every day.) :-)

**Comment by ZAIDI123** [comment]
// Creates a folder that anyone on the Internet can read from and write to. (Domain
// administrators can prohibit this setting for G Suite users.)
var folder = DriveApp.createFolder('Shared Folder');
folder.setSharing(DriveApp.Access.ANYONE, DriveApp.Permission.EDIT);

**Comment by ZAIDI123** [comment]
// Creates a folder that anyone on the Internet can read from and write to. (Domain
// administrators can prohibit this setting for G Suite users.)
var folder = DriveApp.createFolder('Shared Folder');
folder.setSharing(DriveApp.Access.ANYONE, DriveApp.Permission.EDIT);

**Comment by RiKelleher** [comment]
I am also receiving this error today. Is there a fix?
Thanks

**Comment by justcla** [comment]
Fixed and tagged for release as v1.3.1
